const NANOSECONDS = 1;
const MICROSECONDS = 1000 * NANOSECONDS;
const MILLISECONDS = 1000 * MICROSECONDS;
const SECONDS = 1000 * MILLISECONDS;
const MINE_RATE = 4 * SECONDS;
const STARTING_BALANCE = 1000;
const MINING_REWARD = 50;
const MINING_REWARD_INPUT = { address: "*--official-mining-reward--*" };

export {
	NANOSECONDS,
	MICROSECONDS,
	MILLISECONDS,
	SECONDS,
	MINE_RATE,
	STARTING_BALANCE,
	MINING_REWARD,
	MINING_REWARD_INPUT,
};
